services:
  mongodb:
    image: mongo:8
    container_name: backend-challenge-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: backend_challenge

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: